public enum Cmd {
  //--------------------COMMANDS--------------------------------------------------

  //valid SerialCom commands, se SerialCom user manual for more info
  READ_M1_SPEED, READ_M2_SPEED, READ_CUR_1, READ_CUR_2, READ_ENC_CNT, READ_RAW_MTR_SPD, READ_AVG_MTR_SPD, READ_SPD_ERR,
  READ_POS_ERR, READ_BUFFER_LEN, READ_M1_VEL_PID_CONST, READ_M2_VEL_PID_CONST, READ_POS_PID_M1, READ_POS_PID_M2,
  SET_ENC1, SET_ENC2, SET_VEl_PID_CONST1, SET_VEl_PID_CONST2, SET_POS_PID_M1, SET_POS_PID_M2, RESET_ENCS,
  DRIVE_M1_DUTY_CYCL, DRIVE_M2_DUTY_CYCL, DRIVE_BOTH_DUTY_CYCL, DRIVE_M1_SIGN_SPD, DRIVE_M2_SIGN_SPD,
  DRIVE_BOTH_SIGN_SPD, DRIVE_M1_SIGN_SPD_ACL, DRIVE_M2_SIGN_SPD_ACL, DRIVE_BOTH_SIGN_SPD_ACL, DRIVE_M1_SIGN_SPD_DIST,
  DRIVE_M2_SIGN_SPD_DIST, DRIVE_BOTH_SIGN_SPD_DIST, DRIVE_M1_SIGN_SPD_DIST_ACL, DRIVE_M2_SIGN_SPD_DIST_ACL,
  DRIVE_BOTH_SIGN_SPD_DIST_ACL, DRIVE_BOTH_INDIVIDUAL_SIGN_SPD_ACL, DRIVE_BOTH_INDIVIDUAL_SIGN_SPD_ACL_DIST,
  DRIVE_M1_SIGN_DUTY_SPD, DRIVE_M2_SIGN_DUTY_SPD, DRIVE_BOTH_SIGN_DUTY_SPD, DRIVE_M1_SPD_ACL_DCL_POS,
  DRIVE_M2_SPD_ACL_DCL_POS, DRIVE_BOTH_SPD_ACL_DCL_POS, DRIVE_M1_POS, DRIVE_M2_POS, DRIVE_BOTH_POS, DRIVE_M1_SPD_POS,
  DRIVE_M2_SPD_POS, DRIVE_BOTH_SPD_PSO
}
